### ISSUE TITLE
Feature Request: Link concealing 

### ISSUE THREAD

**Issue by cubiquitous** [MeanderingProgrammer/markdown.nvim#10]
Allow conceiling for links. example:

on `mkdnflow`:
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/30845840/5a4a4283-2b7a-40b8-ae5e-a356f6b3c2b4)
when hover:
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/30845840/a4dfcb69-506e-4210-a0b6-654fb0e677a3)

on `markdown.nvim`:
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/30845840/74dfaaf1-3df9-46c6-bcf6-4f395e00c43b)

**Comment by MeanderingProgrammer** [comment]
I've added support for this in the following commit: https://github.com/MeanderingProgrammer/markdown.nvim/commit/c2219984fa1ddc5d3f6a76c1c1ad0744aa9f9011

Turns out various markdown attributes are already concealable by default, users just need to set a high enough conceallevel.

Added support to this plugin to modify conceallevel based on whether the markdown is being rendered or not.

It does mostly what I would like it to do, and is easy enough to opt out of.

Please update the plugin and lmk if this is what you were looking for, thanks!
