### ISSUE TITLE
Showing the text while cursor is on the concelead text

### ISSUE THREAD

**Issue by Faez-Ansari** [MeanderingProgrammer/markdown.nvim#14]
Currently in normal mode everything is concealed but I don't want text to be concelead where my cursor is. Is there a setting for that? I messed with the conceallevel but that didn't make any change. 

Edit:

Better to say that I want to see the raw text where my cursor is.

**Comment by MeanderingProgrammer** [comment]
Hmm, so this depends on what you mean.

Currently the conceal level is applied to the buffer as a whole. So only the things concealed by NeoVim (which I think has to do with tree sitter setting the Conceal highlight group on certain queries) change depending on where the cursor is. An example of this would be links which will have the following states:

- Insert Mode = Raw Text = `[link](https://example.com)`
- Normal Mode with cursor not on line = Concealed Text = `link`
- Normal Mode with cursor on line  = Raw Text = `[link](https://example.com)`

If that is the behavior you're referring to then it should work and I'd need to see some examples to help debug. But if you're referring to the virtual text added by this plugin, like headings and bullet points, we do not a apply a conceal level so where the cursor is has no impact.

From your wording it seems like your expecting the latter behavior, where anything this plugin does goes away if your cursor is on a particular line for that line.

That seems like an interesting feature, I have no idea whether I'd be able to add it. 

My first thought is this would NOT be practically possible since we effectively need the ability to do the opposite of a conceal. 

Meaning normally conceal:

- Cursor on line = show
- Cursor not on line = hide

Whereas here we would need:

- Cursor on line = hide
- Cursor not on line = show

Let me know if that makes sense. I could be missing something in the virtual text options that does this or some other neovim feature that would let us do this easily. But anything that involves running some function every time the cursor moves would be non viable IMO.

**Comment by Faez-Ansari** [comment]
Yes, you've got my point.

I thought the headings and lists were being concealed, not that virtual text was being added. So that explains why the behavior is different from Neovim's conceals. Upon further research, I figured out that the behavior I was looking for is controlled with `concealcursor` option, but that only affects concealed text, not virtual text.

Personally, I don't know whether Neovim offers the mentioned option for virtual text. If there's none, I understand the complexity of its implementation from your explanation, but I think it would be a cool feature to add since it makes editing files easier.

**Comment by MeanderingProgrammer** [comment]
Moving this to a separate issue: https://github.com/MeanderingProgrammer/markdown.nvim/issues/15

**Comment by NikolaM-Dev** [comment]
Is it possible to get the following behavior?

- Cursor on line = hide
- Cursor not on line = hide
- Insert = show

**Comment by MeanderingProgrammer** [comment]
When you say show / hide what are you referring to? Decorations added by this plugin or concealed text or both? An example of what's currently happening and what you'd like to happen instead would be helpful.

**Comment by NikolaM-Dev** [comment]
> When you say show / hide what are you referring to? Decorations added by this plugin or concealed text or both? An example of what's currently happening and what you'd like to happen instead would be helpful.

Thanks for the reply. I actually found what I was looking for in [B0o's config](https://github.com/b0o/dotfiles/blob/1796a4d955d8276ad306f01608e6718388d120a9/config/nvim/lua/user/plugins/langs.lua#L334)

This configuration solves my issue:

```lua
render_modes = { 'n', 'i', 'v', 'V', 'c', 't' },
anti_conceal = { enabled = false },
win_options = {
  concealcursor = { rendered = 'n' },
},
```
