### ISSUE TITLE
deleting bullet from normal makes things weird

### ISSUE THREAD

**Issue by davidosomething** [MeanderingProgrammer/markdown.nvim#2]
```
- [XDG] compliance wherever possible to keep `$HOME` clean
  - See [Arch Linux wiki for XDG Base Directory Support]
  - See [Debian DotFilesList]
  - See [grawity's notes] and [environ notes]
- RC files for Lua, markdownlint, node, PHP, python, R, and others
```

cursor on first bullet, hit `x` to delete

expected: no change to virtual bullets
observed: virtual bullet is rendered on second line first column

**Comment by MeanderingProgrammer** [comment]
Interesting, thanks for reporting this bug!

I found that it only happens if you go from the first item in a list directly to a nested list.

So you get the same bug with this list:

```
- List Item 1
  - Nested List Item
```

But not with this list:

```
- List Item 1
- List Item 2
  - Nested List Item
```

I'll see if I can figure out what's going on with the parser, I imagine something to do with starting with a nested list isn't being handled ideally, I can probably add some simple condition to at least avoid the weird rendering.

**Comment by MeanderingProgrammer** [comment]
Issue should be resolved by: https://github.com/MeanderingProgrammer/markdown.nvim/commit/df98da81375e5dc613c3b1eaa915a847059d48d9
