### ISSUE TITLE
Maintain custom highlights inside tables

### ISSUE THREAD

**Issue by mpasa** [MeanderingProgrammer/markdown.nvim#21]
It seems that custom highlights are lost when matched inside a table cell. 

Example document:

```
# test

foo

| Column1 |
| ------- |
| foo     |
```

Add the syntax and highlights:

```
syn match Custom "foo"
highlight Custom guifg=red
```

Output when editing is showing the styles as expected:

<img width="226" alt="image" src="https://github.com/MeanderingProgrammer/markdown.nvim/assets/5392207/35daef6c-7fdd-4605-aa3f-4045397adc16">

But normal mode rendering is removing the highlight inside the table:

<img width="193" alt="image" src="https://github.com/MeanderingProgrammer/markdown.nvim/assets/5392207/b5a47dd2-470b-4a76-b386-9d380e3be08e">

**Comment by MeanderingProgrammer** [comment]
Make sense.

Since we overlay the entire row with the Normal mode highlight it ends up overwriting any syntax in the cells.

**Comment by MeanderingProgrammer** [comment]
While this is possible to do I'm finding that handling concealing is a problem.

Meaning when we have a link or inline code block in a row, it will get concealed as part of rendering which will misalign the table: like so:

![misaligned](https://github.com/MeanderingProgrammer/markdown.nvim/assets/52591095/0cbaf792-04b1-45ab-b953-285b99cc4992)

Currently this is not a problem since the virtual text that gets overlayed includes all of the raw content without any concealing like so:

![current](https://github.com/MeanderingProgrammer/markdown.nvim/assets/52591095/e78d7de8-c73b-457a-8817-7a4dd8ed76af)

Between these 2 options I definitely prefer the latter.

My thought now is to add the ability to disable rendering of tables entirely if users prefer looking at the highlighted version.

Lmk if you have any thoughts / suggestions.

**Comment by MeanderingProgrammer** [comment]
Concealing is a general behavior of this plugin, added here: https://github.com/MeanderingProgrammer/markdown.nvim/issues/10.

The conceal level gets changed between the rendered view and raw view. As far as I'm aware there is no way to scope options like that to a specific range in a window, so they need to apply to the entire window. Since a table cell can contain any markdown, including links, is just another thing to consider.

I'll add a way of disabling table rendering.

**Comment by mpasa** [comment]
I see. I see this already happens with normal treesitter with concealling enabled. I suppose the only solution would be to modify the nvim-treesitter highlights ([here](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/markdown_inline/highlights.scm#L70)), but that'd be a ton of work.

**Comment by MeanderingProgrammer** [comment]
Added the new behavior here: https://github.com/MeanderingProgrammer/markdown.nvim/commit/49f45978fbb8fcf874f3b6967db4a6ea647df04b

You can now configure the plugin with:

```lua
{ table_style = 'none' }
```

In terms of modifying treesitter directly, apart from the effort, that would end up changing the behavior for everyone, and it does end up just being a preference as opposed to correct / incorrect behavior.

Hopefully this offers a decent middle ground though.

**Comment by mpasa** [comment]
Amazing! Thank you very much, closing the issue now.
