### ISSUE TITLE
Markdown Files Not Rendered Correctly on Horizontal Scroll

### ISSUE THREAD

**Issue by dvnatanael** [MeanderingProgrammer/markdown.nvim#23]
It seems that scrolling horizontally breaks the plugin.

# Steps to Reproduce
0. Open `demo/sample.md` in nvim
1. `:set nowrap`
2. Go to a line that contains text (e.g. line 9)
3. Press `zL` in normal mode

![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/85625605/35829d25-95de-4bd5-8100-ec58e74c663b)

edit: wrong image

**Comment by MeanderingProgrammer** [comment]
I'm honestly not too sure if I want to do anything about this, mostly because long lines in Markdown seem incorrect in general.

The solution would be really expensive in that the auto-command would now need to listen to all cursor movements and re-render the marks with any horizontal offset applied.

If that's what the solution ends up being, and I personally cannot think of a way around it, I would rather leave it as a known limitation of this plugin. Especially when another solution is to have the user enable line wrapping on markdown files.

What do you think?

**Comment by MeanderingProgrammer** [comment]
Pushed a change to eventually disable rendering once the user has scrolled horizontally: https://github.com/MeanderingProgrammer/markdown.nvim/commit/966472e123195cb195e7af49d7db248ce104bee8

I did not want to add an auto-command on all scroll events, since there are just so many of them, so have left that out for the time being.

If there is a better approach to this definitely let me know!

**Comment by dvnatanael** [comment]
Hi, thanks for looking into this. I think that leaving this as a known limitation is perfectly fine, especially since the solution seems to be really expensive.

I'll be sure to let you know if I manage to think of a better approach.
