### ISSUE TITLE
Support for directive admonition syntax

### ISSUE THREAD

**Issue by codingluke** [MeanderingProgrammer/markdown.nvim#25]
Hi @MeanderingProgrammer 

It was a very nice surprise to see, that your fantastic plugin is now supporting GHM callouts! Writing in VIM gets better every day :)

I am wondering if it would be possible to also allow the directive syntax used by all major static site generators?

```markdown
:::note

This is a very important note

:::
```

Best and THX for your freetime!

**Comment by MeanderingProgrammer** [comment]
Thank you for the kind words 🙂

I think this might be getting a little out of scope of a markdown rendering plugin. Since the GHM callouts hijack standard markdown syntax I thought it was reasonable, and it ended up working pretty well. 

Still I will at least attempt this, but if it feels too unrelated to the rest of the plugin I won't add it.

Since I'm not familiar with this syntax can you provide a reference for me? Also is there a tree sitter parser available?

**Comment by MeanderingProgrammer** [comment]
Closing for now, feel free to re-open with some details.

**Comment by redbeardymcgee** [comment]
I am also interested in this enhancement, but I'm not sure if I've found a useful enough reference.

[HERE](https://talk.commonmark.org/t/generic-directives-plugins-syntax/444) is the CommonMark proposal from 2014. [THIS](https://github.com/remarkjs/remark-directive) is the implementation that my docs site depends on, through [Astro Starlight](https://starlight.astro.build/).

I am very grateful for your plugin every day. It makes authoring my docs in nvim a breeze.
