### ISSUE TITLE
Concealing in the title is not working.

### ISSUE THREAD

**Issue by xuwei152** [MeanderingProgrammer/markdown.nvim#34]
The concealing in the title is not working.
![Clip_2024-06-06_23-40-25](https://github.com/MeanderingProgrammer/markdown.nvim/assets/51861161/22e2117b-b458-46a1-8a4f-268b626cc681)

I am using the latest version of the plugin with the default configuration.

**Comment by MeanderingProgrammer** [comment]
What part of the title should be concealed?

If you look at the latex example gif in the README nothing in latex formulas gets concealed.

**Comment by xuwei152** [comment]
I mean "$\Xi^+ K^+K^-$" in "## Study of \$\Xi^+ K^+K^-\$" is concealed. What I expect looks like the picture below.

![Clip_2024-06-07_11-50-39](https://github.com/MeanderingProgrammer/markdown.nvim/assets/51861161/201030c4-81ae-4540-b03d-0edfa280b5b2)

**Comment by MeanderingProgrammer** [comment]
Overlaying the evaluated formula is not something I intend to support, especially with highlighting. You can see some more discussion about this here: https://github.com/MeanderingProgrammer/markdown.nvim/issues/6.

The `LaTeX` support offered by this plugin is pretty minimal and for the foreseeable will involve placing formulas above their source rather than trying to mess with the source directly.
