### ISSUE TITLE
no render after fzf.lua lsp jump

### ISSUE THREAD

**Issue by y1rn** [MeanderingProgrammer/markdown.nvim#36]
###  steps:
-  open lsp document symbols
-  select symbols and select

**Comment by MeanderingProgrammer** [comment]
Thanks for brining this up!

This took some time to figure out, but ended up being caused by `fzf-lua` changing the mode of the underlying buffer between `terminal` and `normal`, as well as a de-sync between scheduling a callback and actually running it.

The latest version should not have this problem. Please update the plugin and lmk if it works.
