### ISSUE TITLE
bug: LaTeX

### ISSUE THREAD

**Issue by Kang-geophysics** [MeanderingProgrammer/markdown.nvim#47]
### Neovim version (nvim -v)

0.10.0

### Operating system

Windows11

### Terminal emulator / GUI

Powershell

### Describe the bug

# Checkhealth.
## Tree-sitter parser status
<img width="284" alt="image" src="https://github.com/MeanderingProgrammer/markdown.nvim/assets/56065588/2da6ed6d-7e22-4236-bf6a-c22f8bc0f72d">

## render-markdown
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/56065588/3998c9b0-cedd-4d96-8842-052d05290120)

# Bug
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/56065588/d622f556-6843-4d00-9b3f-657b2ca98f42)

### Expected behavior

# Question.
I installed `pylatexenc` and latex parser for tree-sitter. As you can see, the `checkhealth` shows there is no problem.
But, the latex equation doesn't work normally.
I don't know the meaning of `<a1><ee>`. I expected the sqrt symbols...

How can I solve this problem?

Thank you for your time.

Sincerely.

### Additional information

I use also WSL. It works well under linux. But it doesn't work in Windows 11.

**Comment by MeanderingProgrammer** [comment]
After spending too long getting a windows setup running I believe this is just due to encoding problems on Windows.

If you get your preferred encoding: https://docs.python.org/3/library/locale.html#locale.getpreferredencoding

```bash
python
import locale
locale.getpreferredencoding()
```

It'll probably give you `cp1252`, which can only do single byte character encodings. The square root symbol requires 2 I believe.

Following the steps here: https://stackoverflow.com/questions/31469707/changing-the-locale-preferred-encoding-in-python-3-in-windows, and restarting your computer should do the trick.

```text
Control panel -> Clock and Region -> Region -> Administrative
-> Change system locale -> Check Beta: Use Unicode UTF-8 ...
```

In either case this is just a Windows thing and if this doesn't work it could be anything from the font to some other long forgotten encoding setting.
