### ISSUE TITLE
[qeustion] fg/bg for the head icon only?

### ISSUE THREAD

**Issue by xixiaofinland** [MeanderingProgrammer/markdown.nvim#51]
I'd like to tweak the fg/bg color for the head icon only instead of the entire heading line. 

It seems `highlights.heading.backgrounds` and `highlights.heading.backgrounds` update the entire line?

**Comment by MeanderingProgrammer** [comment]
Hi, good question, I confused myself for a bit here. Will improve the documentation!

`highlights.heading.foregrounds` applies to the icon only.

Since by default I use the same highlight as the heading, i.e. `markdownH1` for H1s it looks like the foreground stretches the whole line as well, but it does not.

If you change the value for `highlights.heading.foregrounds` you should see a different icon color, with no change to the actual heading text.

**Comment by MeanderingProgrammer** [comment]
Following the latest refactor to group by components the thing you want to modify is `heading.foregrounds`.

**Comment by xixiaofinland** [comment]
works like a charm, thanks!
