### ISSUE TITLE
Feature request: Adding support for math (inline and blocks)

### ISSUE THREAD

**Issue by cnrrobertson** [MeanderingProgrammer/markdown.nvim#6]
One reason I use markdown previewers is to preview math surrounded by `$` or `$$` or ` ```math ` in LaTeX formatting (see [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions) if you need some examples from Github).

It would be awesome if this plugin could overlay the LaTeX text as unicode in the math areas. Of course, implementing a custom parser to do so would probably be overkill, but there is a great Python utility [here](https://github.com/phfaist/pylatexenc) that could be used (as an optional dependency for your package perhaps). In fact, there is Vim plugin that uses this utility to replace LaTeX with rendered text [here](https://github.com/Konfekt/vim-latexencode). From [their example](https://github.com/Konfekt/vim-latexencode/blob/master/autoload/latexencode.vim#L11) it could be really straightforward to implement.

If this is of interest, I could possibly put together a draft PR with the implementation.

One catch is that I don't have any experience working with treesitter, so I'm not sure how easy it is to get the "latex" captures. I think they are there, I'd just need a few pointers.

**Comment by MeanderingProgrammer** [comment]
Hi, and thanks for the suggestion. I can definitely understand the use for something like this.

I don't personally use math expressions often so wouldn't be up for maintaining an entire parser, and it does seem like overkill as you mention.
I'll try using the `pylatexenc` library and see how it turns out, if it works nicely will add the feature. Otherwise will follow up here to see if I can add some support for this kind of thing.

There is definitely a set of features that I don't plan on supporting (like rendering mermaid diagrams) that just get very complex but if there's a way to offload the hard part to a library may as well include it with some instructions.

**Comment by MeanderingProgrammer** [comment]
I have added a basic level of support for LaTeX using the `pylatexenc` library as you suggested in: https://github.com/MeanderingProgrammer/markdown.nvim/commit/138a7962fcbe9cddcb47cc40a58ec0f5ab99ddfe

I'm honestly not sure if I like it, while you do get the rendered characters, you also lose highlighting within the expression. I guess up to the individual on which they prefer.

Let me know what you think and if you have any other suggestions, thanks!

**Comment by cnrrobertson** [comment]
Wow great! Thanks for getting this in so quickly. I agree that its inconvenient to lose the highlighting, but its a great way to get a preview of the math without having to render the whole document. 

One thing I did want to ask about are multiline expressions. Currently, if I put in for example: 

```markdown
$$ 
f(x,y) = \sqrt(y) + \frac{x^2}{4y}
$$
```

the virtual text only replaces the first line with `$$`. Looking at [the source](https://github.com/MeanderingProgrammer/markdown.nvim/blob/38f7cbcc0024737901ba87ee8bf1a6d466f99774/lua/render-markdown/ui.lua#L130-L137) it seems this might be a limitation of the treesitter parser?

**Comment by MeanderingProgrammer** [comment]
Potentially, it's either:

- A limitation of the parser
- There not being a standard way to identify latex within markdown
- I didn't handle it correctly (probably this one)

Github flavored markdown has some of it's own features like the "```math" identifier, which I don't think is supported anywhere else so I think there's going to be some gaps no matter what.

I'll take a look into multi-line support.

**Comment by MeanderingProgrammer** [comment]
I've updated the LaTeX logic to display formulas above the enclosing blocks rather than trying to inline them: https://github.com/MeanderingProgrammer/markdown.nvim/commit/da85a5e5885f1a11ab2b7a9059c16f3eede89bfe.

Let me know how this works for you! I don't have any LaTeX markdown files handy so can't quite tell what makes sense to do.

The real issue would come from many small inline formulas, I imagine those would become less readable.

**Comment by cnrrobertson** [comment]
Wow, thanks again for the very quick response. I like the idea of putting them above - it's not as pretty, but it gives a great preview and keeps the syntax highlighting in the latex inlines and blocks.

You're right about having a lot of small inline formulas, but I don't think that is very common. I have a few readmes that are math heavy and the previews look great for those.

Thanks again!

**Comment by MeanderingProgrammer** [comment]
Awesome, glad its working well enough!

Feel free to suggest ideas / changes after interacting with it some more!

**Comment by life00** [comment]
Hi @MeanderingProgrammer. I wanted to comment on this feature a little bit and suggest some improvements. 

The first thing is that the performance is pretty horrible, or at least the start up time when the file is initially loaded. 200 lines file with a bunch of equations takes to initialize for about 4 seconds when first opened. Well, it works but other tools that I've used did not have this problem.

Also I would like to suggest to replace the code itself with what is rendered, rather than displaying the render above the code. I think this makes more sense. 

I would suggest maybe if its feasible try to implement the concealment yourself in lua (maybe through treesitter?). You might find the following projects relevant. A long time ago I used https://github.com/preservim/vim-markdown which supports concealment of LaTeX math pretty well, however I switched because of performance issues and it overwriting syntax. Currently I am using  https://github.com/vim-pandoc/vim-pandoc-syntax which is simpler and runs much smoother, however its not ideal. 

I don't know either vim or lua much so I am afraid I am not able to help. This is the only crappy part in my neovim setup and I am not sure how to fix it, so unless I find a good alternative I was planning to maybe write my own plugin for this.

**Comment by life00** [comment]
Other relevant resources:
https://gist.github.com/huytd/668fc018b019fbc49fa1c09101363397
https://github.com/Jxstxs/conceal.nvim **!!!**

**Comment by life00** [comment]
Aaand I found my dream plugin I was talking about: https://github.com/ryleelyman/latex.nvim

After researching for a while I understood how to implement math concealment in (neo)vim. The old way is to use `syntax match ...` as linked in previous comment. The new recommended way is through treesitter which requires creating creating custom scheme queries. The above mentioned plugin does that flawlessly.

**Comment by MeanderingProgrammer** [comment]
Thanks for the interest and the enthusiasm!

LaTeX is not something that I use all that often so maintaining a set of rules like in `latex.nvim` is not something I'm up for. But I get the preference. If you want to keep this plugin around for other markdown related things you can disable the latex feature: 

```lua
require('render-markdown').setup({
    latex = { enabled = false },
})
```

And use it in tandem with `latex.nvim`. I don't see a reason why the 2 would interfere with each other.

**Comment by SichangHe** [comment]
Took me a while to figure out, but `latex.nvim` needs `conceallevel = 2` while `render-markdown.nvim` sets it to 3 by default. Just needed to override that.

**Comment by pyrho** [comment]
For anyone else looking I have a setup using [nabla.nvim](https://github.com/jbyuki/nabla.nvim) working with render-markdown nicely.

![CleanShot 2024-10-09 at 21 00 01@2x](https://github.com/user-attachments/assets/8c389695-0772-49c1-abe8-0f8d602557e3)


Here's my setup with lazy.nvim, for nabla:

```lua
{
	"jbyuki/nabla.nvim",
	event = "VeryLazy",
	config = function()
		require("nabla").enable_virt({ autogen = true })
	end,
}
```

for render-markdown:
```lua
return {
	"MeanderingProgrammer/render-markdown.nvim",
	event = "VeryLazy",
	dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" },
	config = function()
		require("render-markdown").setup({
			file_types = { "markdown"},
			latex = { enabled = false },
			win_options = {
				conceallevel = {
					default = vim.api.nvim_get_option_value("conceallevel", {}),
					rendered = 2, -- <- especially this, so that both plugins play nice
				},
			},
		})
	end,
}
```

**Comment by MeanderingProgrammer** [comment]
Added this as another option in the inline latex doc: https://github.com/MeanderingProgrammer/render-markdown.nvim/blob/main/doc/limitations.md#latex-formula-positioning

Thanks!

**Comment by pyrho** [comment]
Awesome thank you! I realized I made a mistake in the config for nabla `require("nabla").enable_virt({ autogen = true })` should be called in a buffer, not at config time. Sorry 😬 .

**Comment by MeanderingProgrammer** [comment]
Ah, thanks for letting me know, I should have tried it out first in either case.

I've added a new `on -> attach` callback you can configure to trigger `nable.nvim` for you: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/8b4149b122cfbf58b79a552ae89b3df2ddc39786

This is in case you want the plugin to always render `latex` rather than triggering it through a keymap or otherwise.

Updated the documentation to reflect this: https://github.com/MeanderingProgrammer/render-markdown.nvim/blob/main/doc/limitations.md#latex-formula-positioning.

**Comment by pyrho** [comment]
Simply incredible, thanks !
