### ISSUE TITLE
Problems  with ordered lists and config defaults

### ISSUE THREAD

**Issue by bertradio** [MeanderingProgrammer/markdown.nvim#7]
I really love the  approach of this plugin.

But it seems to have a problem  with display of ordered lists. Unless they are indented  a couple of times they don't display with  the numbers, only the icons and a "."

So I tried using the full setup config from the help file. That completely crashed the plugin and I had to remove it. Is there an updated version?

Thanks for  the great work!

**Comment by MeanderingProgrammer** [comment]
Thanks for bringing these problems up!

For the latter problem of the config this was due to me using vim.tbl_deep_extend when combining the default config and the user config, which ended up removing the metatable of the query object when a user config is provided.

I updated the configuration to accept a string instead and to do the parsing of the query in the plugin itself: https://github.com/MeanderingProgrammer/markdown.nvim/commit/70f8f4f64d529d60730d6462af180bbec6f7ef18.

So now providing the full configuration as in the README should work.

I hadn't thought of ordered lists, haha, you're right, this does not work for them. Still working on fixing this problem.

**Comment by MeanderingProgrammer** [comment]
Ordered lists should no longer use the bullet point after this change: https://github.com/MeanderingProgrammer/markdown.nvim/commit/f5917d2113ce2b0ce8ce5b24cfbd7f45e0ec5e67

Thanks for reaching out and feel free to re-open if there is still a problem!

**Comment by bertradio** [comment]
Thanks.
