### ISSUE TITLE
feature:  Preview images using graphviz

### ISSUE THREAD

**Issue by mixtli** [MeanderingProgrammer/markdown.nvim#71]
### Is your feature request related to a problem? Please describe.

I love putting diagrams in markdown.   Most of the packages, like graphviz, for example..  have a way to render the image by passing the code as a url to a server which renders the image.   I'd love to be able to render diagrams live in this way.

 

### Describe the solution you'd like

For example, for graphviz:

```
![Alt text](https://g.gravizo.com/svg?
digraph G {
size ="4,4";
main [shape=box];
main -> parse [weight=8];
parse -> execute;
main -> init [style=dotted];
main -> cleanup;
execute -> { make_string; printf}
init -> make_string;
edge [color=red];
main -> printf [style=bold,label="100 times"];
make_string [label="make a string"];
node [shape=box,style=filled,color=".7 .3 1.0"];
execute -> compare;
}
)
```

works in a normal markdown viewer.

Using 3rd/image.nvim I have been able to render images in markdown, but it doesn't render when passing complicated stuff like this.

If you cut and paste that entire url including the code up to ')' in a browser, it renders a diagram.

It'd be really cool to be able to render diagrams from source like this.

### Describe alternatives you've considered

The only way I have to do this now is the render the markdown in a GUI program and iterate that way.

**Comment by MeanderingProgrammer** [comment]
This just comes down to parsing the link within markdown syntax.

According to the markdown tree-sitter parser this `gravizo` link is not a single link. It is a combination of individual links. When I put just your example in a new markdown file and pull the tree this is what I get:

```
(document ; [0, 0] - [17, 0]
  (section ; [0, 0] - [17, 0]
    (paragraph ; [0, 0] - [17, 0]
      (inline ; [0, 0] - [16, 1]
        (inline ; [0, 0] - [16, 1]
          (image ; [0, 0] - [0, 11]
            (image_description)) ; [0, 2] - [0, 10]
          (shortcut_link ; [3, 5] - [3, 16]
            (link_text)) ; [3, 6] - [3, 15]
          (shortcut_link ; [4, 14] - [4, 24]
            (link_text)) ; [4, 15] - [4, 23]
          (shortcut_link ; [6, 13] - [6, 27]
            (link_text)) ; [6, 14] - [6, 26]
          (shortcut_link ; [10, 5] - [10, 16]
            (link_text)) ; [10, 6] - [10, 15]
          (shortcut_link ; [11, 15] - [11, 45]
            (link_text)) ; [11, 16] - [11, 44]
          (shortcut_link ; [12, 12] - [12, 35]
            (link_text)) ; [12, 13] - [12, 34]
          (shortcut_link ; [13, 5] - [13, 47]
            (link_text))))))) ; [13, 6] - [13, 46]
```

Whereas this example:

```
![Alt text](demo/test.png)
```

Produces the following tree:

```
(document ; [0, 0] - [1, 0]
  (section ; [0, 0] - [1, 0]
    (paragraph ; [0, 0] - [1, 0]
      (inline ; [0, 0] - [0, 26]
        (inline ; [0, 0] - [0, 26]
          (image ; [0, 0] - [0, 26]
            (image_description) ; [0, 2] - [0, 10]
            (link_destination))))))) ; [0, 12] - [0, 25]
```

I think if you format the link to avoid new lines and use some escape characters in the URL `images.nvim` will be able to pull it for you since it can get images from URLs, however that would make editing it for you much more difficult.

Since I am not going custom parse this and do not want that kind of logic inside this plugin I unfortunately can't implement this.

Maybe there's something to do with how `images.nvim` gets the link, but if it also relies on treesitter I imagine we end up in the same situation.
