### ISSUE TITLE
feature: auto-setup on ftplugin/markdown?

### ISSUE THREAD

**Issue by mrcjkb** [MeanderingProgrammer/markdown.nvim#79]
### Is your feature request related to a problem? Please describe.

I have to call a `setup` function to be able to use this plugin.

See also: https://github.com/nvim-neorocks/nvim-best-practices?tab=readme-ov-file#zap-initialization

Some plugin managers (lazy.nvim, rocks with rocks-config.nvim) provide hacks to work around this issue. But it can be painful if you're not using one of those plugin managers.

### Describe the solution you'd like

It would be nice if `setup` were only used for configuration, and this plugin could auto-initialise (using the default config if no `setup` was called) when opening a markdown file.

This can be achieved by moving the initialisation logic to a script in `ftplugin/markdown.lua`.

### Describe alternatives you've considered

N/A

### Additional information

Here's how it's done in markview.nvim: https://github.com/OXY2DEV/markview.nvim/blob/316cafc79490f8b79c288bbe6638838d6d68e227/ftplugin/markdown.lua

**Comment by MeanderingProgrammer** [comment]
While `markview` is limited to `markdown` files this plugin is not. It is meant to work with any `filetype` that has injected markdown. A common example I've seen is `vimwiki` which changes the filetype of `markdown` files.

Since the filetype is dynamic the `ftplugin` approach doesn't quite work.

Is there another approach that might work for this situation? Maybe just using the standard `plugin` directory to call `setup`?

**Comment by mrcjkb** [comment]
> Maybe just using the standard plugin directory to call setup?

Yes, that would work too. 
In that case I would recommend [to be careful about lazy-loading modules](https://github.com/nvim-neorocks/nvim-best-practices?tab=readme-ov-file#is-your-plugin-not-filetype-specific-but-it-likely-wont-be-needed-every-single-time-a-user-opens-a-neovim-session).

**Comment by MeanderingProgrammer** [comment]
I think I have an approach to do this but would really appreciate any feedback / advice.

The main problem is that I'm using a configuration parameter `file_types` as the `pattern` for the main `FileType` autocommand. In this case it is impossible to decouple configuration from initialization (though I could be missing something), since the configuration has to happen first before an autocommand can safely be created. This happens here: https://github.com/MeanderingProgrammer/markdown.nvim/blob/main/lua/render-markdown/manager.lua#L22.

A simple way around this would be to remove the `pattern` from the autocommand, so listen to everything for that event, and move the file type filter into the `callback`. That way when when the configuration changes the `callback` will pick it up, unlike the autocommand pattern which is stuck. This makes sense as an approach to me, but I'm unsure if this has its own downsides, other than a mild performance hit. Maybe it makes more sense to delete and re-create the autocommand but for some reason that approach seems worse?

Is it generally a bad idea to call vim apis directly with user configured values? Since when you call the API you're stuck with whatever the configuration was at the time of call. Maybe more of a problem in some cases than others.

Thanks in advance!

**Comment by mrcjkb** [comment]
:thinking: with Neovim's built-in initialization sequence, this wouldn't be a problem, since `init.lua` is sourced before any `plugin` scripts.
But I suppose it could be a problem for lazy.nvim users, since it calls its `config` hook (where users usually call `setup` functions) *after* sourcing `plugin` scripts.

One possibility would be to tell lazy.nvim users to set any options that need to be set before the plugin is initialized in lazy.nvim's `init` hook (which would be more in line with Neovim's built-in behaviour).

Another (hacky) option that works with lazy.nvim would be to delay the creation of the autocommand:

```lua
--- plugin/markview.lua
local timer = vim.uv.new_timer()
timer:start(
  500,
  0,
  vim.schedule_wrap(function()
    -- create autocommand in here
  end)
)
```

> A simple way around this would be to remove the pattern from the autocommand, so listen to everything for that event, and move the file type filter into the callback. That way when when the configuration changes the callback will pick it up, unlike the autocommand pattern which is stuck. This makes sense as an approach to me, but I'm unsure if this has its own downsides, other than a mild performance hit. Maybe it makes more sense to delete and re-create the autocommand but for some reason that approach seems worse?

This definitely sounds like the cleanest option to me. And I doubt the performance impact would be measurable as long as you're only loading a lightweight `config` module that doesn't need to load any other modules.

Or, you could defer the creation of the `FileType` autocommand to an event like `BufReadPre`:

```lua
--- plugin/markview.lua
vim.api.nvim_create_autocmd("BufReadPre", {
  once = true,
  callback = function()
    -- create FileType autocommand in here
  end,
  group = ...
})
```

> Is it generally a bad idea to call vim apis directly with user configured values? Since when you call the API you're stuck with whatever the configuration was at the time of call. Maybe more of a problem in some cases than others.

I would say it depends on whether you want the behaviour to be hot-swappable at runtime. I usually follow the YAGNI principle and don't worry about it unless people ask for it.

**Comment by MeanderingProgrammer** [comment]
Thanks for the response! 

Creating the `FileType` autocommand inside of another autocommand is an interesting idea. I thought about it but ultimately decided on the removing pattern approach. Just because it's a little easier for me to understand what's going on. But maybe I'll be able to use that idea for something else :)

I merged the change here: https://github.com/MeanderingProgrammer/markdown.nvim/commit/67bdd9b68c6519bf1d5365f10c96107032bb4532.

Feel free to re-open if you have any concerns!

Thanks again for the suggestion and the advice!

**Comment by mrcjkb** [comment]
Awesome 🚀 

And thank you 🙏
