### ISSUE TITLE
feature: add html_tag conceal & arrows rendering?

### ISSUE THREAD

**Issue by kevinm6** [MeanderingProgrammer/markdown.nvim#96]
### Is your feature request related to a problem? Please describe.

Hi, really nice plugin.
Could it possible add conceal for:

- `html_tag`, I can find it useful especially in some `<u>Hello World</u>` to be just 'Hello World’ underlined or other similar usages
- arrows in markdown replaced by default icons or chosen by user:
  - `&rarr;`: &rarr;
  - `&larr;`: &larr;
  - `&uarr;`: &uarr;
  - `&darr;`: &darr;
  - `&harr;`: &harr;
  - `&lrarr;`: &lrarr;  

### Describe the solution you'd like

For the arrows, I was already using these queries for **treesitter** for `markdown_inline`:

```scheme
((entity_reference) @conceal (#eq? @conceal "&rarr;") (#set! conceal ""))
((entity_reference) @conceal (#eq? @conceal "&larr;") (#set! conceal ""))
((entity_reference) @conceal (#eq? @conceal "&uarr;") (#set! conceal ""))
((entity_reference) @conceal (#eq? @conceal "&darr;") (#set! conceal ""))
```

..and this for the **html_tag**:

```scheme
(inline (html_tag) @conceal (#set! conceal “”))
```

### Describe alternatives you've considered

Use a **custom query** for `markdown_inline` as I’m already doing

**Comment by MeanderingProgrammer** [comment]
I gave it some thought, kind of went back and forth, but I think for now I'm going to stay out of the HTML parsing space.

I appreciate the idea, and there's nothing wrong with it, other than I don't put HTML in markdown and don't want to open up that can of worms. Currently the plugin stays pretty tightly connected to basic markdown syntax and I think that's where I'm going to keep it.

The various arrow entities living in users highlight extensions is probably the right way to go. You can potentially try to put this in nvim-treesitter where there are some entity replacements already: https://github.com/nvim-treesitter/nvim-treesitter/blame/master/queries/markdown_inline/highlights.scm#L100, though maybe since these are icons as opposed to standard characters they might also prefer to have users configure it themselves.

This plugin does offer an extension point if you want to try adding the HTML concealing yourself: https://github.com/MeanderingProgrammer/markdown.nvim/blob/main/doc/custom-handlers.md, happy to help if you wanna try it out.
